spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  redis:
    host: localhost
    lettuce:
      pool:
        min-idle: 10
        max-active: 30
        max-idle: 30
        max-wait: 10000
  thymeleaf:
    cache: false

logging:
  level:
    root: info
    com.example.blog.dao: debug
